import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const HomeLink = () => <Link href="/">Home</Link>

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HomeLink></HomeLink>
        <header>
          {children}
        </header>
      </body>
    </html>
  )
}
